(ns inventist.schoolsoft.client.examples)

(comment "Groups look like this comming from schoolsoft"
         {:maxstudent    "0",
          :description   "Åk 9",
          :classtype     "1",
          :leavepickup   "0",
          :mentortype    "1",
          :name          "Åk 9",
          :resourcetype  "0",
          :reviewtype    "1",
          :active        "1",
          :id            "271",
          :classplanning "1",
          :externalid    "{F95BADFC-E432-4268-8264-49BF02965DE2}"}
         {:maxstudent    "0",
          :description   "Åk 9:a",
          :classtype     "0",
          :leavepickup   "0",
          :mentortype    "0",
          :name          "Åk 9:a",
          :resourcetype  "0",
          :reviewtype    "1",
          :active        "1",
          :id            "176",
          :classplanning "0",
          :externalid    "{5F3E0A72-CF01-4777-9576-EA690B41B6E5}"})

(comment "Students"
         {:lastlogin          "2018-03-29 15:30",
          :pocode             "64731",
          :email              "emilia@live.se",
          :logincount         "5124",
          :fname              "Emilia",
          :sex                "f",
          :socialnumber       "020909-0000",
          :city               "Mariefred",
          :username           "emilia.arman",
          :contactinfo        "",
          :absencemessagetype "-1",
          :notpublish         "0",
          :lname              "Example",
          :address1           "Redacted 9",
          :homephone          "",
          :workphone          "",
          :address2           "",
          :active             "1",
          :id                 "243",
          :picture            "student243.jpg",
          :swimmingability    "0",
          :mobile             "0708283947",
          :classid            "271"})


(comment "Teachers"
         {:lastlogin    "2018-03-25 15:12",
          :pocode       "",
          :email        "fanny.orsa@gripsholmsskolan.se",
          :logincount   "259",
          :fname        "Fanny",
          :socialnumber "870506-0000",
          :city         "",
          :username     "fanny.orsa",
          :type         "0",
          :contactinfo  "",
          :lname        "Örså",
          :address1     "",
          :homephone    "",
          :workphone    "",
          :address2     "",
          :active       "1",
          :id           "38",
          :initial      "FÖ",
          :mobile       ""})
